/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ZeroXKeepLockerInterface extends Interface {
    getFunction(nameOrSignature: "LOCK_FEE" | "VESTING_FEE" | "claimVesting" | "createVesting" | "feeReceiver" | "lockToken" | "userLocks" | "userVestings" | "withdrawLock"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Locked" | "Vested" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'LOCK_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'VESTING_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimVesting', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createVesting', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeReceiver', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockToken', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userLocks', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userVestings', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawLock', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'LOCK_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VESTING_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeReceiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userLocks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userVestings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawLock', data: BytesLike): Result;
  }

  
    export namespace LockedEvent {
      export type InputTuple = [token: AddressLike, user: AddressLike, amount: BigNumberish, unlockTime: BigNumberish, lockId: BigNumberish];
      export type OutputTuple = [token: string, user: string, amount: bigint, unlockTime: bigint, lockId: bigint];
      export interface OutputObject {token: string, user: string, amount: bigint, unlockTime: bigint, lockId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VestedEvent {
      export type InputTuple = [token: AddressLike, user: AddressLike, amount: BigNumberish, duration: BigNumberish, vestingId: BigNumberish];
      export type OutputTuple = [token: string, user: string, amount: bigint, duration: bigint, vestingId: bigint];
      export interface OutputObject {token: string, user: string, amount: bigint, duration: bigint, vestingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [token: AddressLike, user: AddressLike, amount: BigNumberish, lockType: string, id: BigNumberish];
      export type OutputTuple = [token: string, user: string, amount: bigint, lockType: string, id: bigint];
      export interface OutputObject {token: string, user: string, amount: bigint, lockType: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZeroXKeepLocker extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZeroXKeepLocker;
    waitForDeployment(): Promise<this>;

    interface: ZeroXKeepLockerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    LOCK_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VESTING_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimVesting: TypedContractMethod<
      [_token: AddressLike, _vestingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createVesting: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _durationSeconds: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    feeReceiver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lockToken: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _unlockTime: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    userLocks: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [[bigint, bigint, boolean] & {amount: bigint, unlockTime: bigint, withdrawn: boolean }],
      'view'
    >
    

    
    userVestings: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {totalAmount: bigint, claimedAmount: bigint, startTime: bigint, duration: bigint }],
      'view'
    >
    

    
    withdrawLock: TypedContractMethod<
      [_token: AddressLike, _lockId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'LOCK_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VESTING_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimVesting'): TypedContractMethod<
      [_token: AddressLike, _vestingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createVesting'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _durationSeconds: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'feeReceiver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lockToken'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _unlockTime: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'userLocks'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [[bigint, bigint, boolean] & {amount: bigint, unlockTime: bigint, withdrawn: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'userVestings'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {totalAmount: bigint, claimedAmount: bigint, startTime: bigint, duration: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawLock'): TypedContractMethod<
      [_token: AddressLike, _lockId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Locked'): TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
getEvent(key: 'Vested'): TypedContractEvent<VestedEvent.InputTuple, VestedEvent.OutputTuple, VestedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Locked(address,address,uint256,uint256,uint256)': TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
      Locked: TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
    

      'Vested(address,address,uint256,uint256,uint256)': TypedContractEvent<VestedEvent.InputTuple, VestedEvent.OutputTuple, VestedEvent.OutputObject>;
      Vested: TypedContractEvent<VestedEvent.InputTuple, VestedEvent.OutputTuple, VestedEvent.OutputObject>;
    

      'Withdrawn(address,address,uint256,string,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }